### ISSUE TITLE
Use the mojohaus icon which is used on github for the web site

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/mojo-parent#20]

**Comment by mfriedenhagen** [comment]
@khmarbaise, do you where I may get this picture? I may copy the avatar, but I guess there is a SVG lurking in the dark :grin:

**Comment by lennartj** [comment]
Hello folks.

I made the image - and called it `MojoHausTmpLogo.png` because I just wanted something other than the GitHub standard word-art-y icon until a better logo could be made.


![mojohaustmplogo](https://cloud.githubusercontent.com/assets/906157/8982048/b1f5a5f0-36bd-11e5-887b-b4ca968d4b83.png)

**Comment by mfriedenhagen** [comment]
@lennartj, great. I think I will just put this into the site project and other project may reference it from there. I intend to just overwrite the existing logo.

**Comment by mfriedenhagen** [comment]
Hi, @lennartj do you have a SVG as well?
