### ISSUE TITLE
Github report should be sorted on release version

### ISSUE THREAD

**Issue by andham** [mojohaus/mojo-parent#48]
Currently (mojo-parent 40) the Github report is  sorted on issue number, which makes it hard to see what has been fixed in what release. Change that so it is sorted on release version.

**Comment by khmarbaise** [comment]
First upgrade to 2.12.1 of maven-changes-plugin second adding configuration like this:
```xml
<configuration>
  <githubAPIServerId>github</githubAPIServerId>
  <githubAPIScheme>https</githubAPIScheme>
  <includeOpenIssues>false</includeOpenIssues>
  <onlyMilestoneIssues>true</onlyMilestoneIssues>
  <runOnlyAtExecutionRoot>true</runOnlyAtExecutionRoot> 
  <onlyCurrentVersion>true</onlyCurrentVersion>
</configuration>
```
If you like to use it locally you have to create a personal access token and configuring that in the settings.xml file instead of the password.

**Comment by khmarbaise** [comment]
The disadvantage of this is: Making a release requires an access token in your github account as well as the configuration in `settings.xml` as well.

**Comment by khmarbaise** [comment]
Currently I'm thinking about removing the whole github page and make the release notes available via https://github.com/mojohaus/mojo-parent/releases (more more detailed like this https://github.com/khmarbaise/maven-it-extension/releases) or maybe even better via https://github.com/marketplace/actions/release-drafter in a more automated way.

**Comment by andham** [comment]
IMO we shouldn't forget that Maven plugins are focused around their maven site. If we have the release notes in github we should at least have a link there from the site.

**Comment by khmarbaise** [comment]
This is fine for me. +1

**Comment by khmarbaise** [comment]
So after testing some parts the release drafter is not the correct one cause it only uses pull request which is not enough for us. 

The following is the result using a [github-release-notes-generator](https://github.com/spring-io/github-release-notes-generator) (from my own command line; I'm trying to get a way to get that running automatically while a milestone is closed). But I think the content looks ok:
@andham  WDYT?

Using the following configuration:
```yaml
  sections:
    - title: "Bug Fixes"
      emoji: "🐞"
      labels: ["bug"]
    - title: "Enhancements"
      emoji: "⭐"
      labels: ["enhancement"]
    - title: "Dependency Upgrades"
      emoji: "🔨"
      labels: ["dependency-upgrade"]
    - title: "Documentation"
      emoji: "📔"
      labels: ["documentation"]
```
----- 
## 🐞 Bug Fixes

- Fixes #82 ensure version change affects only the current directory (and child directories), not the parent or sibling directories [#400](https://github.com/mojohaus/versions-maven-plugin/pull/400)
- Warning if plugin is executed in parallel [#373](https://github.com/mojohaus/versions-maven-plugin/issues/373)

## ⭐ Enhancements

- Remove cobertura-maven-plugin  [#409](https://github.com/mojohaus/versions-maven-plugin/issues/409)
- Removed plexus-i18n [#405](https://github.com/mojohaus/versions-maven-plugin/issues/405)
- Fixes #321 fail the build when parsing XML of child modules fails due to invalid XML [#399](https://github.com/mojohaus/versions-maven-plugin/pull/399)
- Upgrade GitHub Actions [#398](https://github.com/mojohaus/versions-maven-plugin/issues/398)
- Ensure display output is order, only order at point of printing [#394](https://github.com/mojohaus/versions-maven-plugin/pull/394)
- use-latest-versions ignores dependencies with versions defined as properties [#340](https://github.com/mojohaus/versions-maven-plugin/issues/340)

## 🔨 Dependency Upgrades

- Upgrade modello-maven-plugin from 1.9.1 to 1.11 [#410](https://github.com/mojohaus/versions-maven-plugin/issues/410)
- Upgrade plugin version for versions-maven-plugin from 2.4 to 2.7 [#408](https://github.com/mojohaus/versions-maven-plugin/issues/408)
- Upgrade doxia from 1.7 to 1.9.1 [#407](https://github.com/mojohaus/versions-maven-plugin/issues/407)
- Upgrade wagon from 2.12 to 3.4.0 [#406](https://github.com/mojohaus/versions-maven-plugin/issues/406)
- Upgrade plexus-interactivity-api from 1.0-alpha-6 to 1.0 [#404](https://github.com/mojohaus/versions-maven-plugin/issues/404)
- Upgrade plexus-container-default from 1.7.1 to 2.1.0 [#403](https://github.com/mojohaus/versions-maven-plugin/issues/403)
- Upgrade hamcrest-library from 1.3 to hamcrest-core 2.2 [#402](https://github.com/mojohaus/versions-maven-plugin/issues/402)
- Upgrade mockito 1.9.5 to 2.28.2 [#401](https://github.com/mojohaus/versions-maven-plugin/issues/401)
- Upgrade woodstox-core-asl from 4.2.0 to 4.4.1 [#397](https://github.com/mojohaus/versions-maven-plugin/issues/397)
- Upgrade maven-common-artifact-filters to 3.1.0 [#389](https://github.com/mojohaus/versions-maven-plugin/issues/389)
- Upgrade plexus-utils to 3.3.0 [#388](https://github.com/mojohaus/versions-maven-plugin/issues/388)
- commons-lang3 v3.9 [#380](https://github.com/mojohaus/versions-maven-plugin/pull/380)

## :heart: Contributors

We'd like to thank all the contributors who worked on this release!

- [@stefanseifert](https://github.com/stefanseifert)
- [@nhojpatrick](https://github.com/nhojpatrick)

**Comment by andham** [comment]
@khmarbaise So the release notes would then be in Github? And we would have a link from the mojo site? The L&F is ok with me.

**Comment by khmarbaise** [comment]
Yes the resulting release notes would be put into the [release pages on GitHub](https://github.com/mojohaus/mojo-parent/releases) (#113) and a link in the generated site of the released state as well.

**Comment by mfriedenhagen** [comment]
I am all for this. Looking for release-info directly on GitHub is what people are used to nowadays.
